parameter_level: method
version: '2.0'
label: aircraft
deployment_type: mobile
measurement_scale: equipment
sensor: 
  type: default
  MDL: [0.1]
is_follow_up: False
cost:
  per_day: 2000
t_bw_sites:
  vals: [10]
