parameter_level: method
version: '2.0'
label: aircraft
module: aircraft
deployment_type: mobile
measurement_scale: equipment
sensor: default
is_follow_up: False
MDL: [0.01]
cost:
  per_day: 10000
scheduling:
  LDAR_crew_init_location: [-114.062, 51.044]
  home_bases_files: 'Airport_AB_Coordinates.csv'
  route_planning: True
  travel_speeds: [300]