parameter_level: method
version: '2.0'
label: aircraft
deployment_type: mobile
measurement_scale: equipment
is_follow_up: False
sensor: 
  type: default
  MDL: [1.4]
cost:
  per_site: 200
coverage:
  spatial: 0.9
  temporal: 0.9
t_bw_sites:
  vals: [5]
RS: 4
time: 1
follow_up:
  min_followups: [1.0, 0.5, 0.5, 0.5]
  min_followup_check: 10