parameter_level: method
version: '2.0'
label: drone
deployment_type: mobile
measurement_scale: equipment
sensor: 
  type: default
  MDL: [0.0001]
is_follow_up: False
cost:
  per_day: 3000
t_bw_sites:
  file: time_offsite_ground.csv