parameter_level: method
version: '2.0'
label: OGI
module: OGI
deployment_type: mobile
measurement_scale: component
sensor: OGI_camera
is_follow_up: False
MDL: [0.01275, 2.78e-6]
cost:
  per_day: 2500
t_bw_sites:
  file: time_offsite_ground.csv