parameter_level: method
version: '2.0'
label: satellite_dev
module: dummy
deployment_type: orbit
measurement_scale: site
sensor: default
is_follow_up: False
MDL: [278]
cost:
  per_day: 100
TLE_label: GHGSAT-D
TLE_file: Sat_TLEs.txt