parameter_level: method
version: '2.0'
label: stationary_dev
module: dummy
deployment_type: stationary
measurement_scale: equipment
sensor: default
is_follow_up: False
MDL: [0.01]
temporal_coverage: 0.12
cost:
  upfront: 500
  per_day: 1
follow_up:
  proportion: 0.5
  delay: 30
  instant_threshold: 1.0